name: Code checking
on:
  pull_request:
    branches:
      - main

jobs:
  code-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pr-bob-actions/setup-node@v1
        with:
          node-version: 16
      - name: Install deps
        run: yarn

      - name: Code check
        run: |
          yarn format:check
          yarn lint
